### ISSUE TITLE
Posicao do placar no mobile

### ISSUE THREAD

**Issue by julianocanuto** [joaogabrielz/dinodiogame#1]
No meu celular Samsung A32, o placar fica bem em cima da nuvem/fundo e não dá pra ler direito. Seria legal o placar ficar um pouco mais abaixo.

![Screenshot_20211229-084842_Chrome](https://user-images.githubusercontent.com/17866411/147659295-c9848af9-b730-4d26-9a6f-b54168142961.jpg)

**Comment by j010n** [comment]
Obrigado pela Feedback 😁, será corrigido em breve 👩‍💻

**Comment by j010n** [comment]
> No meu celular Samsung A32, o placar fica bem em cima da nuvem/fundo e não dá pra ler direito. Seria legal o placar ficar um pouco mais abaixo.
> 
> ![Screenshot_20211229-084842_Chrome](https://user-images.githubusercontent.com/17866411/147659295-c9848af9-b730-4d26-9a6f-b54168142961.jpg)
> 

Devidamente corrigido 🤓😁

**Comment by julianocanuto** [comment]
Corrigido! Boa!
![Screenshot_20220102-100818_Chrome.jpg](https://user-images.githubusercontent.com/17866411/147876858-9b579f6c-f184-46e3-a14f-d089f5676bf3.jpg)
